title: 李宏 | Li Hong — Homepage
page-top-title: 李宏
top-section-bg-text: Towards reliable training & intelligent decisions
home-subtitle: Li Hong&nbsp;｜&nbsp;东南大学 · 交通工程 · 统计学（硕士拟入学）
copyright-text: '&copy; Li Hong 2022–2026. All Rights Reserved.'
